# Bhakti Javiya
# 216270307098

In [ ]:
'''Write a Pandas program to implement following operation

to convert a NumPy array to a Pandas series'''

import numpy as np
import pandas as pd
arr=np.array([1,2,3,4,5,6])
print("NumPy array:")
print(arr)
print("Converted Pandas series:")
print(pd.Series(arr))

In [ ]:
'''to convert the first column of a DataFrame as a Series'''

import pandas as pd
technologies = {
    'Courses':["Java","Mada","Graphic designing","Python","Php"],
    'Fee' :[28000,15000,36000,26000,55000],
    'Duration':['30days','35days','45days','50days','70days'],
    'Discount':[2000,2100,2600,2300,4000]
              }
df = pd.DataFrame(technologies)
print(df)

# Get first column as a series
df2 = df.iloc[:, 0]
print(df2)

In [ ]:
'''to create the mean and standard deviation of the data of a given Series
'''

s = pd.Series(data = [1,2,3,4,5,6,7,8,9,10,11,12])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

In [ ]:
'''to sort a given Series'''

import pandas as pd
s = pd.Series(['100', '600', 'Mada', '400.21', '300'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print("Sorted Series:")
print(new_s)